- name: Associate configuration item to the requested item
  hosts: localhost
  gather_facts: false

  tasks:
    - ansible.builtin.debug:
        var: ci_number

    - name: Get sys_id for RITM number
      servicenow.itsm.api_info:
        resource: sc_req_item
        sysparm_query: numberSTARTSWITH{{ request_item_number }}
      register: ritm_lookup


    - name: Associate change request to the requested item
      servicenow.itsm.api:
        resource: sc_req_item
        action: patch
        sys_id: "{{ ritm_lookup.record[0].sys_id }}"
        data:
          configuration_item: "{{ ci_number }}"